#!/usr/bin/env bash

webapp-run() {
    docker compose -f compose.yml run webapp "$@"
}

webapp() {
    docker compose -f compose.yml exec webapp "$@"
}

psql() {
    docker compose -f compose.yml exec db psql -U pguser "$@"
}

proxy() {
    docker compose -f compose.yml exec proxy "$@"
}

proxy-reload() {
    docker compose -f compose.yml exec proxy caddy reload --config /etc/caddy/Caddyfile "$@"
}

proxy-fmt() {
    docker compose -f compose.yml exec proxy caddy fmt /etc/caddy/Caddyfile "$@"
}

compose() {
    docker compose -f compose.yml "$@"
}

ruby() {
    docker run \
        --workdir=/usr/src/app \
        --volume=/$(pwd)/webapp:/usr/src/app \
        ruby "$@"
}

"$@"
