services:

  db:
    image: postgres:15
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - private
    ports:
      - 5432:5432

  db_admin:
    image: adminer
    hostname: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - private

  webapp:
    image: ruby:3
    hostname: rails
    build:
      context: webapp
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
      - cache
    networks:
      - private
    volumes:
      - ./webapp:/usr/src/app
      - bundle-cache:/bundle
    environment:
      DATABASE_URL: "postgresql://pguser:pgpassword@postgres:5432/app"
      REDIS_URL: "redis://:redispassword@redis:6379/0"

  cache:
    image: redis:7
    build:
      context: cache
      dockerfile: Dockerfile
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - private

  proxy:
    image: caddy:2
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    restart: always
    hostname: nginx
    depends_on:
      - webapp
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "./proxy/Caddyfile:/etc/caddy/Caddyfile"
      - "./webapp/public:/srv"
      - "caddy-data:/data"
      - "caddy-config:/config"
    networks:
      - private
      - public

volumes:
  pg-data:
  bundle-cache:
  caddy-data:
  caddy-config:

networks:
  public:
  private:
